# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Zihao Wang, Postdoctoral Appointee at Argonne National Lab, specializes in surface chemistry and thin films deposition. Explore my work on catalysts, oxidation reactions, and sustainable materials.'
    twitter: ''
  analytics:
    google_analytics: 'G-GV1JV8L76F'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
    microsoft_clarity: 'mrlf9dox0x'
  verification:
    google: 'rPPH6c6o9KD8UpQuba1oYI33-wwULiTZKnUNYgS-XrA'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Zihao Wang"

# Site footer
footer:
  copyright:
    notice: '© {year} Zihao Wang. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
